/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./src/components/area/AreaSelect.vue')['default']
    AreaSelectAsync: typeof import('./src/components/area/AreaSelectAsync.vue')['default']
    BarSimple: typeof import('./src/components/echartsCom/BarSimple.vue')['default']
    DateSelect: typeof import('./src/components/date/DateSelect.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    ModelSelector: typeof import('./src/components/select/ModelSelector.vue')['default']
    PieBorderRadius: typeof import('./src/components/echartsCom/PieBorderRadius.vue')['default']
    RoleFilter: typeof import('./src/components/role/roleFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slogan: typeof import('./src/components/slogan.vue')['default']
    UploadFile: typeof import('./src/components/file/uploadFile.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WecomUserSelect: typeof import('./src/components/wecomUser/wecomUserSelect.vue')['default']
  }
}
